import type { AiProvider } from "./provider";

export class MockProvider implements AiProvider {
  async generateJson<T>(): Promise<T> {
    throw new Error("MockProvider output is generated by the local pipeline");
  }
}
